credentials:
  usernames:
    guanjia:
      email: jsmith@gmail.com
      name: 储兵兵
      password: guanjia # To be replaced with hashed password
cookie:
  expiry_days: 5
  key: random_signature_key # Must be string
  name: random_cookie_name
preauthorized:
  emails:
  - melsby@gmail.com